fabrnetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core import views

urlpatterns = [
    path(r'manutencao/', views.manutencao, name='manutencao'),
	path(r'', views.index, name='index'),
    path(r'compare/', views.compare, name='compare'),
    path(r'compactos/', views.compacts, name='compacts'),
    path(r'contato/', views.contact, name='contact'),
    path(r'campeonatos/', include('championship.urls', namespace='championship')),
    path(r'estatisticas/', include('statistic.urls', namespace='statistic')),
    path(r'times/', include('team.urls', namespace='team')),
	path(r'noticias/', include('news.urls', namespace='news')),
    path(r'loja/', views.store, name='store'),
    path('admin/', admin.site.urls),
    path(r'summernote/', include('django_summernote.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path, re_path

from . import views

app_name = 'news'

urlpatterns = [
    path('', views.news_list, name='news_list'),
    re_path(r'^(?P<slug>[\w_-]+)/$', views.news, name='news'),
]

statistic/urls.py
from django.urls import path, re_path

from . import views

app_name = 'statistic'

urlpatterns = [
    re_path(r'^$', views.statisticRedirect, name='statisticRedirect'),
    re_path(r'^(?P<slug>[\w_-]+)/$', views.seasonRedirect, name='statisticSeasonRedirect'),
    re_path(r'^(?P<slug>[\w_-]+)/(?P<conference>[\w_-]+)/$', views.StatisticDetailView,
        name='statistic_championship'),
    re_path(r'^(?P<slug>[\w_-]+)/$', views.StatisticDetailView, name='statistic_championship')

]

statistic/models.py
from django.db import models

from championship.models import Game
from team.models import SubTeam, Team, Player

# Create your models here.
class EventType(models.Model):
    team_category = models.ForeignKey(SubTeam, on_delete=models.CASCADE, verbose_name='Time')
    name = models.CharField('Tipo', max_length=255)
    points = models.IntegerField('Pontos', default=0)

    class Meta:
        verbose_name='Tipo de jogada'
        verbose_name_plural='Tipos de jogadas'
        ordering=['team_category', 'name']

    def __str__(self):
        return str(self.name) + ' (' + str(self.team_category) + ')'


class Period (models.Model):
    name = models.CharField('Período', null=True, blank=True, max_length=50)

    class Meta:
        verbose_name='Período'
        verbose_name_plural='Períodos'
        ordering=['name']

    def __str__(self):
        return str(self.name)


class Event (models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE, verbose_name='Jogo')
    event_type = models.ForeignKey(EventType, on_delete=models.CASCADE, verbose_name='Tipo de evento')
    playerA = models.ForeignKey(Player, related_name='playerA',
        on_delete=models.CASCADE, verbose_name='Jogador A')
    playerB = models.ForeignKey(Player, related_name='playerB', blank=True, null=True, on_delete=models.CASCADE, verbose_name='Jogador B')
    period = models.ForeignKey(Period, on_delete=models.CASCADE, blank=True, null=True, 
        verbose_name='Período')

    created = models.DateTimeField('Criado', auto_now_add=True)
    modified = models.DateTimeField('Modificado', auto_now=True)

    class Meta:
        verbose_name='Evento'
        verbose_name_plural='Eventos'
        ordering=['-game']

    def __str__(self):
        return str(self.game) + ' ' + str(self.event_type) + ':' + str(self.playerA) + str(self.playerB)

statistic/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.db.models import Count, Q

from .models import Event
from championship.models import Championship, Season, Conference, Division, Game 
from team.models import Team

# Create your views here.
class StatisticDetailView(generic.DetailView):
    model = Season
    template_name = 'statistic.html'
    context_object_name = 'season'

    def _filter_by_team(self, games, team):
        events = Event.objects.filter(game__in=games, 
            event_type__team_category__name=team).values('playerA__team', 'event_type__points').annotate(
            total=Count('playerA__team')).order_by('playerA__team')[:10]
        
        category = {}
        for e in events:
            team = Team.objects.get(id=e['playerA__team'])
            if team in category:
                category[team] += e['total']*e['event_type__points']
            else:
                category[team] = e['total']*e['event_type__points']
        
        category = sorted(category.items(), key=lambda x: x[1], reverse=True)

        return category


    def _filter_by_team_inverse(self, games, team):
        events = Event.objects.filter(game__in=games, event_type__team_category__name=team).values(
            'game__teamA', 'game__teamB', 'playerA__team', 'event_type__points')


        category = {}
        for e in events:
            if e['playerA__team'] == e['game__teamA']:
                team = Team.objects.get(id=e['game__teamB'])
            else:
                team = Team.objects.get(id=e['game__teamA'])
            
            if team not in category:
                    category[team] = 0
            category[team] += e['event_type__points']
        
        category = sorted(category.items(), key=lambda x: x[1], reverse=False)[:10]
        
        return category

    def _filter_by_event_type(self, games, event_type):
        events = Event.objects.filter(game__in=games, 
            event_type__name=event_type).values('playerA__team').annotate(
            total=Count('playerA__team')).order_by('playerA__team')[:10]
        
        category = {}
        for e in events:
            category[Team.objects.get(id=e['playerA__team'])] = e['total']
        
        category = sorted(category.items(), key=lambda x: x[1], reverse=True)

        return category

    def _filter_by_multiple_event_types(self, games, list_event_types):
        events = Event.objects.filter(game__in=games, 
            event_type__name__in=list_event_types).values('playerA__team').annotate(
            total=Count('playerA__team')).order_by('playerA__team')[:10]
        
        category = {}
        for e in events:
            category[Team.objects.get(id=e['playerA__team'])] = e['total']
        
        category = sorted(category.items(), key=lambda x: x[1], reverse=True)

        return category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        championships = Championship.objects.all()
        championship = self.object.championship
        seasons = Season.objects.filter(championship=self.object.championship)
        season = self.object
        conferences = Conference.objects.filter(season=self.object)
        conference = Conference.objects.filter(season=self.object,
                name=self.kwargs.get('conference', None)).first()
        if conference:
            divisions = Division.objects.filter(conference=conference)
            teams = []
            for division in divisions:
                teams.append(division.teams.all())
            teams = [item for sublist in teams for item in sublist]
            games = Game.objects.filter(Q(week__season=self.object),
                (Q(teamA__in=teams) | Q(teamB__in=teams)))
        else:
            conference = 'Todas'
            games = Game.objects.filter(week__season=self.object)


        attack = self._filter_by_team(games, 'Ataque')
        defense = self._filter_by_team_inverse(games, 'Ataque')
        special = self._filter_by_team(games, 'Time Especial')

        touchdown = self._filter_by_multiple_event_types(games,
            ['Touchdown passe', 'Touchdown corrida', 'Touchdown', 'Retorno de fumble', 'Pick six'])
        pass_touchdown = self._filter_by_event_type(games, 'Touchdown passe')
        run_touchdown = self._filter_by_event_type(games, 'Touchdown corrida')
        
        defense_touchdown = self._filter_by_multiple_event_types(games, ['Retorno de fumble', 'Pick six'])
        special_team_touchdown = self._filter_by_event_type(games, 'Touchdown')
        safety = self._filter_by_event_type(games, 'Safety')

        context = {
            'championships': championships,
            'championship': championship,
            'seasons': seasons,
            'season': season,
            'conferences':conferences,
            'conference': conference,
            'attack': attack,
            'defense': defense,
            'special': special,
            'touchdown': touchdown,
            'pass_touchdown': pass_touchdown,
            'run_touchdown': run_touchdown,
            'defense_touchdown': defense_touchdown,
            'special_team_touchdown': special_team_touchdown,
            'safety': safety
        }

        return context

StatisticDetailView = StatisticDetailView.as_view()

def seasonRedirect(request, slug):
    season = Season.objects.filter(slug__contains=slug).first()
    return redirect('/estatisticas/'+season.slug+'/'+ 'Todas')

def statisticRedirect(request):
    season = Season.objects.filter(slug__contains='bfa').first()
    
    return redirect('/estatisticas/'+season.slug+'/'+'Todas')

statistic/templates/statistic.html
{% extends 'base.html' %}

{% load static %}

{% block container %}
<style type="text/css">
        :root{
            --primaryColor: #F4F4F4;
            --secundaryColor: {{ league.secundaryColor }};
            --terciaryColor: {{ league.terciaryColor }};
        }
    </style>

<div class="page-header" id="banner">
    <div class="row">
        <div class="btn-group" style="margin-left: 20px;">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"> <span id="selected">Campeonato</span><br/>
                <span class="selected-item">{{championship.shortName}}</span>
                <i class="fa fa-xs fa-angle-down selected-angle"></i>
            </button>
            <ul class="dropdown-menu dropdown-team">
                {% for c in championships %}
                    {% if c != championship %}
                        <li><a href="{% url 'statistic:statistic_championship' slug=c.shortName|lower %}">{{c.shortName}}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        <div class="btn-group" style="margin-left: 20px;">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"> <span id="selected">Temporada</span><br/>
                <span class="selected-item">{{season.year}}</span>
                <i class="fa fa-xs fa-angle-down selected-angle"></i>
            </button>
            <ul class="dropdown-menu dropdown-team">
                {% for s in seasons %}
                    {% if s != season %}
                        <li><a href="{% url 'statistic:statistic_championship' slug=s.slug %}">{{s.year}}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        <div class="btn-group" style="margin-left: 20px;">
            <button type="button" class="btn btn-default dropdown-toggle" style="padding-right: 55px;" data-toggle="dropdown"> <span id="selected">Conferência</span><br/>
                <span class="selected-item">
                    {% if conference.name %}
                        {{ conference.name }}
                    {% else %}
                        {{conference}}
                    {% endif %}</span>
                <i class="fa fa-xs fa-angle-down selected-angle"></i>
            </button>
            <ul class="dropdown-menu dropdown-team">
                {% if conference != 'Todas' %}
                    <li><a href="{% url 'statistic:statistic_championship' slug=season.slug %}">Todas</a></li>
                {% endif %}
                {% for conf in conferences %}
                    {% if conf != conference %}
                        <li><a href="{% url 'statistic:statistic_championship' slug=season.slug conference=conf.name %}">{{conf.name}}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
        <table class="table table-standings">
            <thead class="table-header">
                <tr>
                    <th></th>
                  <th id="group">Ataque</th>
                  <th>P</th>
                </tr>
             </thead>
            <tbody>
                {% for team,points in attack %}
                    <tr>
                        <td id='col'>{{ forloop.counter }}</td>
                        <td id="name"><img class="mini-photo" src="{{ team.logo.url }}">{{ team.name }}</td>
                        <td id="col">{{ points }}</td>
                    </tr>
                {% endfor %}
            </tbody>       
        </table>
    </div>
        <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
        <table class="table table-standings">
            <thead class="table-header">
                <tr>
                    <th></th>
                  <th id="group">Defesa</th>
                  <th>P</th>
                </tr>
             </thead>
            <tbody>
                {% for team,points in defense %}
                    <tr>
                        <td id='col'>{{ forloop.counter }}</td>
                        <td id="name"><img class="mini-photo" src="{{ team.logo.url }}">{{ team.name }}</td>
                        <td id="col">{{ points }}</td>
                    </tr>
                {% endfor %}
            </tbody>      
        </table>
    </div>
        <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
        <table class="table table-standings">
            <thead class="table-header">
                <tr>
                    <th></th>
                  <th id="group">Time Especial</th>
                  <th>P</th>
                </tr>
             </thead>
            <tbody>
                {% for team,points in special %}
                    <tr>
                        <td id='col'>{{ forloop.counter }}</td>
                        <td id="name"><img class="mini-photo" src="{{ team.logo.url }}">{{ team.name }}</td>
                        <td id="col">{{ points }}</td>
                    </tr>
                {% endfor %}
            </tbody>       
        </table>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
        <table class="table table-standings">
            <thead class="table-header">
                <tr>
                    <th></th>
                  <th id="group">Touchdown</th>
                  <th>N</th>
                </tr>
             </thead>
            <tbody>
                {% for team,points in touchdown %}
                    <tr>
                        <td id='col'>{{ forloop.counter }}</td>
                        <td id="name"><img class="mini-photo" src="{{ team.logo.url }}">{{ team.name }}</td>
                        <td id="col">{{ points }}</td>
                    </tr>
                {% endfor %}
            </tbody>       
        </table>
    </div>
        <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
        <table class="table table-standings">
            <thead class="table-header">
                <tr>
                    <th></th>
                  <th id="group">Touchdown / Passe</th>
                  <th>N</th>
                </tr>
            </thead>
            <tbody>
                {% for team,number in pass_touchdown %}
                    <tr>
                        <td id='col'>{{ forloop.counter }}</td>
                        <td id="name"><img class="mini-photo" src="{{ team.logo.url }}">{{ team.name }}</td>
                        <td id="col">{{ number }}</td>
                    </tr>
                {% endfor %}
            </tbody>       
        </table>
    </div>
        <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
        <table class="table table-standings">
            <thead class="table-header">
                <tr>
                    <th></th>
                  <th id="group">Touchdown / Corrida</th>
                  <th>N</th>
                </tr>
             </thead>
            <tbody>
                {% for team,number in run_touchdown %}
                    <tr>
                        <td id='col'>{{ forloop.counter }}</td>
                        <td id="name"><img class="mini-photo" src="{{ team.logo.url }}">{{ team.name }}</td>
                        <td id="col">{{ number }}</td>
                    </tr>
                {% endfor %}
            </tbody>       
        </table>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
        <table class="table table-standings">
            <thead class="table-header">
                <tr>
                    <th></th>
                  <th id="group">Touchdown / Defesa</th>
                  <th>N</th>
                </tr>
             </thead>
            <tbody>
                {% for team,number in defense_touchdown %}
                    <tr>
                        <td id='col'>{{ forloop.counter }}</td>
                        <td id="name"><img class="mini-photo" src="{{ team.logo.url }}">{{ team.name }}</td>
                        <td id="col">{{ number }}</td>
                    </tr>
                {% endfor %}
            </tbody>       
        </table>
    </div>
    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
        <table class="table table-standings">
            <thead class="table-header">
                <tr>
                    <th></th>
                  <th id="group">Touchdown / Time Especial</th>
                  <th>N</th>
                </tr>
             </thead>
            <tbody>
                {% for team,number in special_team_touchdown %}
                    <tr>
                        <td id='col'>{{ forloop.counter }}</td>
                        <td id="name"><img class="mini-photo" src="{{ team.logo.url }}">{{ team.name }}</td>
                        <td id="col">{{ number }}</td>
                    </tr>
                {% endfor %}
            </tbody>       
        </table>
    </div>
    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
        <table class="table table-standings">
            <thead class="table-header">
                <tr>
                    <th></th>
                  <th id="group">Safety</th>
                  <th>N</th>
                </tr>
            </thead>
            <tbody>
                {% for team,number in safety %}
                    <tr>
                        <td id='col'>{{ forloop.counter }}</td>
                        <td id="name"><img class="mini-photo" src="{{ team.logo.url }}">{{ team.name }}</td>
                        <td id="col">{{ number }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}