championship/urls.py
from django.urls import path, re_path

from . import views

app_name = 'championship'

urlpatterns = [
    re_path(r'^$', views.championship_list, name='championship_list'),
    re_path(r'^playoffs/(?P<slug>[\w_-]+)/(?P<week>[\w_-]+)/$', views.SeasonDetailView, name='seasonPlayoffs'),
    re_path(r'^(?P<slug>[\w_-]+)/$', views.seasonRedirect, name='seasonRedirect'),
    re_path(r'^(?P<slug>[\w_-]+)/(?P<week>[\w_-]+)/$', views.SeasonDetailView, name='season'),
]

fabrnetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core import views

urlpatterns = [
    path(r'manutencao/', views.manutencao, name='manutencao'),
	path(r'', views.index, name='index'),
    path(r'compare/', views.compare, name='compare'),
    path(r'compactos/', views.compacts, name='compacts'),
    path(r'contato/', views.contact, name='contact'),
    path(r'campeonatos/', include('championship.urls', namespace='championship')),
    path(r'estatisticas/', include('statistic.urls', namespace='statistic')),
    path(r'times/', include('team.urls', namespace='team')),
	path(r'noticias/', include('news.urls', namespace='news')),
    path(r'loja/', views.store, name='store'),
    path('admin/', admin.site.urls),
    path(r'summernote/', include('django_summernote.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path, re_path

from . import views

app_name = 'news'

urlpatterns = [
    path('', views.news_list, name='news_list'),
    re_path(r'^(?P<slug>[\w_-]+)/$', views.news, name='news'),
]

statistic/urls.py
from django.urls import path, re_path

from . import views

app_name = 'statistic'

urlpatterns = [
    re_path(r'^$', views.statisticRedirect, name='statisticRedirect'),
    re_path(r'^(?P<slug>[\w_-]+)/$', views.seasonRedirect, name='statisticSeasonRedirect'),
    re_path(r'^(?P<slug>[\w_-]+)/(?P<conference>[\w_-]+)/$', views.StatisticDetailView,
        name='statistic_championship'),
    re_path(r'^(?P<slug>[\w_-]+)/$', views.StatisticDetailView, name='statistic_championship')

]

team/urls.py
from django.urls import path, re_path

from . import views

app_name = 'team'

urlpatterns = [
    #Outros templates
    re_path(r'^$', views.teams, name='teams'),
    re_path(r'^divisao/(?P<slug>[\w_-]+)/$', views.teams_category, name='teams_category'),
    re_path(r'^compare/$', views.LikenView, name='liken'),
    re_path(r'^(?P<slug>[\w_-]+)/$', views.ScheduleListView, name='team'),
    re_path(r'^(?P<slug>[\w_-]+)/elenco/$', views.RosterView, name='roster'),
    re_path(r'^(?P<slug>[\w_-]+)/agenda/$', views.ScheduleListView, name='schedule'),
    re_path(r'^(?P<slug>[\w_-]+)/agenda/(?P<year>[\w_-]+)$', views.ScheduleByYearView, name='schedule_year'),
    re_path(r'^(?P<slug>[\w_-]+)/compactos/$', views.CompactListView, name='compact'),
    re_path(r'^(?P<slug>[\w_-]+)/campanhas/$', views.CampaignDatailView, name='campaign'),
    re_path(r'^(?P<slug>[\w_-]+)/instagram/$', views.InstagramDetailView, name='instagram'),
    re_path(r'^(?P<slug>[\w_-]+)/facebook/$', views.FacebookDetailView, name='facebook'),
    re_path(r'^(?P<slug>[\w_-]+)/historia/$', views.HistoryDetailView, name='history'),
    re_path(r'^(?P<slug>[\w_-]+)/(?P<playerSlug>[\w_-]+)/$', views.player, name='player'),
]

core/models.py
from django.db import models

# Create your models here.


class Slide (models.Model):
    description = models.CharField('Descrição', max_length=255)
    photo = models.ImageField(
        'Foto', upload_to='players/photo/')
    link = models.URLField(
        'Link', max_length=5000)
    subtitle = models.CharField('Legenda', max_length=100, blank=True)

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = 'Slide'
        verbose_name_plural = 'Slides'

class Region (models.Model):
    name = models.CharField('Nome', max_length=255)

    class Meta:
        verbose_name = 'Região'
        verbose_name_plural = 'Regiões'
        ordering = ['name']

    def __str__(self):
        return self.name


class State (models.Model):
    code = models.IntegerField(
        'Código', null=False, blank=False, primary_key=True)
    name = models.CharField('Nome', max_length=255)
    uf = models.CharField('Unidade Federativa', max_length=20)
    region = models.ForeignKey(
        Region, on_delete=models.CASCADE, verbose_name='Região', null=True, blank=True)

    class Meta:
        verbose_name = 'Estado'
        verbose_name_plural = 'Estados'
        ordering = ['name']

    def __str__(self):
        return self.uf


class City (models.Model):
    code = models.IntegerField(
        'Código', null=False, blank=False, primary_key=True)
    name = models.CharField('Nome', max_length=255)
    uf = models.ForeignKey(State, on_delete=models.CASCADE,
                           verbose_name='Estado', null=True, blank=True)

    class Meta:
        unique_together = (('name', 'uf'),)
        verbose_name = 'Cidade'
        verbose_name_plural = 'Cidades'
        ordering = ['name']

    def __str__(self):
        return self.name + ' - ' + str(self.uf)

statistic/models.py
from django.db import models

from championship.models import Game
from team.models import SubTeam, Team, Player

# Create your models here.
class EventType(models.Model):
    team_category = models.ForeignKey(SubTeam, on_delete=models.CASCADE, verbose_name='Time')
    name = models.CharField('Tipo', max_length=255)
    points = models.IntegerField('Pontos', default=0)

    class Meta:
        verbose_name='Tipo de jogada'
        verbose_name_plural='Tipos de jogadas'
        ordering=['team_category', 'name']

    def __str__(self):
        return str(self.name) + ' (' + str(self.team_category) + ')'


class Period (models.Model):
    name = models.CharField('Período', null=True, blank=True, max_length=50)

    class Meta:
        verbose_name='Período'
        verbose_name_plural='Períodos'
        ordering=['name']

    def __str__(self):
        return str(self.name)


class Event (models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE, verbose_name='Jogo')
    event_type = models.ForeignKey(EventType, on_delete=models.CASCADE, verbose_name='Tipo de evento')
    playerA = models.ForeignKey(Player, related_name='playerA',
        on_delete=models.CASCADE, verbose_name='Jogador A')
    playerB = models.ForeignKey(Player, related_name='playerB', blank=True, null=True, on_delete=models.CASCADE, verbose_name='Jogador B')
    period = models.ForeignKey(Period, on_delete=models.CASCADE, blank=True, null=True, 
        verbose_name='Período')

    created = models.DateTimeField('Criado', auto_now_add=True)
    modified = models.DateTimeField('Modificado', auto_now=True)

    class Meta:
        verbose_name='Evento'
        verbose_name_plural='Eventos'
        ordering=['-game']

    def __str__(self):
        return str(self.game) + ' ' + str(self.event_type) + ':' + str(self.playerA) + str(self.playerB)

core/views.py
from django.shortcuts import render

from .models import Slide
from championship.models import Championship

# Create your views here.
def manutencao (request):
    return render (request, 'manutencao.html')

def index (request):
    context = {
        'slides':Slide.objects.all()[:3]
    }
    return render (request, 'home.html', context)

def compare (request):
    return render (request, 'compare.html')

def compacts(request):
    return render(request, 'compacts.html')

def contact(request):
    return render(request, 'contato.html')

def store(request):
    return render(request, 'store.html')

statistic/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.db.models import Count, Q

from .models import Event
from championship.models import Championship, Season, Conference, Division, Game 
from team.models import Team

# Create your views here.
class StatisticDetailView(generic.DetailView):
    model = Season
    template_name = 'statistic.html'
    context_object_name = 'season'

    def _filter_by_team(self, games, team):
        events = Event.objects.filter(game__in=games, 
            event_type__team_category__name=team).values('playerA__team', 'event_type__points').annotate(
            total=Count('playerA__team')).order_by('playerA__team')[:10]
        
        category = {}
        for e in events:
            team = Team.objects.get(id=e['playerA__team'])
            if team in category:
                category[team] += e['total']*e['event_type__points']
            else:
                category[team] = e['total']*e['event_type__points']
        
        category = sorted(category.items(), key=lambda x: x[1], reverse=True)

        return category


    def _filter_by_team_inverse(self, games, team):
        events = Event.objects.filter(game__in=games, event_type__team_category__name=team).values(
            'game__teamA', 'game__teamB', 'playerA__team', 'event_type__points')


        category = {}
        for e in events:
            if e['playerA__team'] == e['game__teamA']:
                team = Team.objects.get(id=e['game__teamB'])
            else:
                team = Team.objects.get(id=e['game__teamA'])
            
            if team not in category:
                    category[team] = 0
            category[team] += e['event_type__points']
        
        category = sorted(category.items(), key=lambda x: x[1], reverse=False)[:10]
        
        return category

    def _filter_by_event_type(self, games, event_type):
        events = Event.objects.filter(game__in=games, 
            event_type__name=event_type).values('playerA__team').annotate(
            total=Count('playerA__team')).order_by('playerA__team')[:10]
        
        category = {}
        for e in events:
            category[Team.objects.get(id=e['playerA__team'])] = e['total']
        
        category = sorted(category.items(), key=lambda x: x[1], reverse=True)

        return category

    def _filter_by_multiple_event_types(self, games, list_event_types):
        events = Event.objects.filter(game__in=games, 
            event_type__name__in=list_event_types).values('playerA__team').annotate(
            total=Count('playerA__team')).order_by('playerA__team')[:10]
        
        category = {}
        for e in events:
            category[Team.objects.get(id=e['playerA__team'])] = e['total']
        
        category = sorted(category.items(), key=lambda x: x[1], reverse=True)

        return category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        championships = Championship.objects.all()
        championship = self.object.championship
        seasons = Season.objects.filter(championship=self.object.championship)
        season = self.object
        conferences = Conference.objects.filter(season=self.object)
        conference = Conference.objects.filter(season=self.object,
                name=self.kwargs.get('conference', None)).first()
        if conference:
            divisions = Division.objects.filter(conference=conference)
            teams = []
            for division in divisions:
                teams.append(division.teams.all())
            teams = [item for sublist in teams for item in sublist]
            games = Game.objects.filter(Q(week__season=self.object),
                (Q(teamA__in=teams) | Q(teamB__in=teams)))
        else:
            conference = 'Todas'
            games = Game.objects.filter(week__season=self.object)


        attack = self._filter_by_team(games, 'Ataque')
        defense = self._filter_by_team_inverse(games, 'Ataque')
        special = self._filter_by_team(games, 'Time Especial')

        touchdown = self._filter_by_multiple_event_types(games,
            ['Touchdown passe', 'Touchdown corrida', 'Touchdown', 'Retorno de fumble', 'Pick six'])
        pass_touchdown = self._filter_by_event_type(games, 'Touchdown passe')
        run_touchdown = self._filter_by_event_type(games, 'Touchdown corrida')
        
        defense_touchdown = self._filter_by_multiple_event_types(games, ['Retorno de fumble', 'Pick six'])
        special_team_touchdown = self._filter_by_event_type(games, 'Touchdown')
        safety = self._filter_by_event_type(games, 'Safety')

        context = {
            'championships': championships,
            'championship': championship,
            'seasons': seasons,
            'season': season,
            'conferences':conferences,
            'conference': conference,
            'attack': attack,
            'defense': defense,
            'special': special,
            'touchdown': touchdown,
            'pass_touchdown': pass_touchdown,
            'run_touchdown': run_touchdown,
            'defense_touchdown': defense_touchdown,
            'special_team_touchdown': special_team_touchdown,
            'safety': safety
        }

        return context

StatisticDetailView = StatisticDetailView.as_view()

def seasonRedirect(request, slug):
    season = Season.objects.filter(slug__contains=slug).first()
    return redirect('/estatisticas/'+season.slug+'/'+ 'Todas')

def statisticRedirect(request):
    season = Season.objects.filter(slug__contains='bfa').first()
    
    return redirect('/estatisticas/'+season.slug+'/'+'Todas')

core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-135013867-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-135013867-1');
  </script>

    <meta charset="utf-8">
    <meta property="og:image" content="https://raw.githubusercontent.com/filipecmedeiros/FABR-Network/master/design/site%203.0/1.2%20-%20campeonato%20classifica%C3%A7%C3%A3o.jpg">
    <meta property="og:image:type" content="image/jpg">
    <meta property="og:image:width" content="679">
    <meta property="og:image:height" content="1521">

    <title>{% block title %}FABR Network {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'assets/bootstrap.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'assets/custom.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
  </head>
  <body>
    <div class="container">
      <div class="pull-left logo hidden-sm hidden-md hidden-xs">
        <a href="{% url 'index' %}"><img class="img-responsive" src="{% static 'img/fabr-logo.png' %}" style="height:100px; margin-bottom:10px;"></a>
      </div>
      <div class="pull-right searchbox hidden-sm hidden-md hidden-xs">
        <ul class="nav navbar-nav social-media">
          <li class="social-media">
            <a href="https://www.facebook.com/fabrnetwork/" class="fa fa-facebook-square fa-lg social-media" target="_blank"></a>
          </li>
          <li class="social-media">
            <a href="https://www.instagram.com/fabrnetwork/" class="fa fa-instagram fa-lg social-media" target="_blank"></a>
          </li>
          <li class="social-media">
            <a href="https://www.twitter.com/fabrnetwork/" class="fa fa-twitter-square fa-lg social-media" target="_blank"></a>
          </li>
          <!--<li class="social-media">
              <a href="https://www.youtube.com/fabrhighlights1" class="fa fa-youtube-play fa-lg social-media" target="_blank"></a>
            </li>
          <li>
            <form class="navbar-form navbar-right">
            <input type="text" class="form-control col-lg-8" placeholder="Pesquise">
            <span class="">
              <button class="btn btn-info fa fa-search" type="button"/>
            </span>
            </form>
          </li>-->
        </ul>
        
      </div>
    </div>
    <div class="container">
      <div class="navbar navbar-default">
        <div class="container">
            <div class="pull-left hidden-lg">
              <a href="{% url 'index' %}"><img class="img-responsive" style="max-width:100px;" src="{% static 'img/fabr-logo.png' %}" style="height:100px; margin-bottom:10px;"></a>
            </div>
        <div class="navbar-header">
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
            <ul class="nav navbar-nav">
                <li class="top-menu {% if request.resolver_match.view_name in 'championship:season' or request.resolver_match.view_name in 'championship:championship_list' %}current_page{% endif %}">
                    <a href="{% url 'championship:championship_list' %}">
                        <img src="{% static 'img/top-menu/campeonatos.png' %}" style="margin-left:7px;"> 
                        <span>Campeonatos</span>
                    </a>
                </li>
                <li class="top-menu {% if request.resolver_match.view_name in 'team:teams' %}current_page{% endif %}">
                  <a href="{% url 'team:teams' %}">
                        <img src="{% static 'img/top-menu/times.png' %}"> 
                        <span>Times</span>
                    </a>
                </li>
                <li class="top-menu {% if request.resolver_match.view_name in 'news:news_list' %}current_page{% endif %}">
                    <a href="{% url 'news:news_list' %}">
                        <img src="{% static 'img/top-menu/noticias.png' %}"> 
                        <span>Notícias</span>
                    </a>
                </li>
                <li class="top-menu" >
                    <a href="{% url 'statistic:statisticRedirect' %}" id="estatistica">
                        <img src="{% static 'img/top-menu/estatisticas.png' %}"> 
                        <span>Estatísticas</span>
                    </a>
                </li>
                <!-- <li class="top-menu">
                  <a id="compactos">
                        <img src="{% static 'img/top-menu/compactos.png' %}"> 
                        <span>Compactos  <i style="font-size:1.2rem; padding-bottom:2px;" class="fa fa-lock"></i></span>
                    </a>
                </li>-->
                <li class="top-menu">
                  <a href="{% url 'store' %}">
                        <img src="{% static 'img/top-menu/loja.png' %}"> 
                        <span>Loja</span>
                    </a>
                </li>
                <li class="top-menu {% if request.resolver_match.view_name in 'contact' %}current_page{% endif %}">
                    <a href="{% url 'contact' %}">
                        <img src="{% static 'img/top-menu/contato.png' %}"> 
                        <span>Contato</span>
                    </a>
                </li>
            </ul>
      
        </div>
      </div>
    </div>
  </div>
  </div>
    <div class="container">
      {% block container %}
      {% endblock %}
    </div>
    {% block footer %}
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 footer">
        <div class="row">
          <a href="{% url 'index' %}">
            <img src="{% static 'img/logo-mono.png' %}" class="img-responsive fabr-logo-gray">
          </a>
          <hr>
        </div>
        <div class="row">
          <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
          </div>
          <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
            <ul class="nav flex-column footer-list">
              <li class="nav-item"><a href="{% url 'team:teams' %}">TIMES</a></li>
              <li class="nav-item"><a href="{% url 'team:teams_category' 'elite' %}">Elite</a></li>
              <li class="nav-item"><a href="{% url 'team:teams_category' 'acesso' %}">Acesso</a></li>
              <li class="nav-item"><a href="{% url 'team:teams_category' 'outros' %}">Outros</a></li>
              <li class="nav-item"><a href="{% url 'team:teams_category' 'inativos' %}">Inativos</a></li>
            </ul>
          </div>
          <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
            <ul class="nav flex-column footer-list">
              <li class="nav-item"><a href="{% url 'news:news_list' %}">NOTÍCIAS</a></li>
              <li class="nav-item"><a href="{% url 'news:news_list' %}">Últimas</a></li>
            </ul>
          </div>
          <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
            <ul class="nav flex-column footer-list">
              <li class="nav-item"><a href="{% url 'championship:seasonRedirect' 'bfa' %}">CAMPEONATO</a></li>
              <li class="nav-item"><a href="{% url 'championship:seasonRedirect' 'bfa' %}">BFA</a></li>
              <li class="nav-item"><a href="{% url 'championship:seasonRedirect' 'bfa' %}">CBFA</a></li>
              <li class="nav-item"><a href="{% url 'championship:seasonRedirect' 'ttd' %}">TTD</a></li>
            </ul>
          </div>
          <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
            <ul class="nav flex-column footer-list">
              <li class="nav-item"><a href="{% url 'contact' %}">CONTATO</a></li>
            </ul>
          </div>
          <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
          </div> 
        </div>
          <br/>
          <br/>
          <br/>
          <div class="row">
            <h3 class="copyright">Copyright 2017-2018-2019-2020 FABR Network, Filipe Medeiros e Haim Ferreira| Todos os direitos reservados</h3>
          </div>
      </div>
    {% endblock %}
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'assets/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/usebootstrap.js' %}"></script>
    <script src="{% static 'js/scroll-sneak.js' %}"></script>

  </body>
</html>

core/templates/compacts.html
{% extends 'base.html' %}

{% block title %}
	Compactos | {{block.super}}
{% endblock %}

{% load static %}

{% block container %}
  <div class="page-header" id="banner">
      <div class="page-header" id = "banner">
      <div class="col-lg-12 col-md-12">
        <ul class="list-inline">
          <li>
            <div class="btn-group" style="margin-top: 30px; margin-bottom:30px;">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"> <span id="selected">Campeonato</span><br/>
              <span class="selected-item">LNFA</span>
              <i class="fa fa-xs fa-angle-down selected-angle"></i>
              </button>
              <ul class="dropdown-menu dropdown-team">
                  <li><a href="#">BFA</a></li>
              </ul>
            </div>
        </li>
        <li>
          <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"> <span id="selected">Temporada</span><br/>
            <span class="selected-item">2018</span>
            <i class="fa fa-xs fa-angle-down selected-angle"></i>
            </button>
            <ul class="dropdown-menu dropdown-team">
                <li><a href="#">2017</a></li>
                <li><a href="#">2016</a></li>
            </ul>
          </div>
        </li>
        <li style="margin-left:40px;">
          <div class="btn-group">
            <button type="button" class="btn btn-week btn-success"><span class="selected-item">1</span></button>
            <button type="button" class="btn btn-week"><span class="selected-item">2</span></button>
            <button type="button" class="btn btn-week"><span class="selected-item">3</span></button>
            <button type="button" class="btn btn-week"><span class="selected-item">4</span></button>
            <button type="button" class="btn btn-week"><span class="selected-item">5</span></button>
            <button type="button" class="btn btn-week"><span class="selected-item">6</span></button>
            <button type="button" class="btn btn-week"><span class="selected-item">7</span></button>
            <button type="button" class="btn btn-week"><span class="selected-item">8</span></button>
            <button type="button" class="btn btn-week"><span class="selected-item">9</span></button>
            <button type="button" class="btn btn-week"><span class="selected-item">10</span></button>
            <button type="button" class="btn btn-week"><span class="selected-item">11</span></button>
            <button type="button" class="btn btn-week"><span class="selected-item">12</span></button>
            <button type="button" class="btn btn-week"><span class="selected-item">13</span></button>
            <button type="button" class="btn btn-week"><span class="selected-item">14</span></button>
            <button type="button" class="btn btn-week"><span class="selected-item">15</span></button>
            <button type="button" class="btn btn-week"><span class="selected-item">16</span></button>
          </div>
        </li>
      </ul>
    </div>
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <iframe class="col-lg-12 col-md-12 col-sm-12 col-xs-12 watch" height="400" src="https://www.youtube.com/embed/YJeHWZEzLJI" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div id="carousel-main" class="carousel slide " data-ride="carousel" data-interval="5000">
          <!-- Carousel items -->
          <div class="carousel-inner">
              <div class="active item">
                <img class="img-responsive compact-carousel" src="http://i1.ytimg.com/vi/YJeHWZEzLJI/mqdefault.jpg">
                <img class="img-responsive compact-carousel" src="http://i1.ytimg.com/vi/YJeHWZEzLJI/mqdefault.jpg">
                <img class="img-responsive compact-carousel" src="http://i1.ytimg.com/vi/YJeHWZEzLJI/mqdefault.jpg">
                <img class="img-responsive compact-carousel" src="http://i1.ytimg.com/vi/YJeHWZEzLJI/mqdefault.jpg">
              </div>
              <div class="item">
                <img class="img-responsive compact-carousel" src="http://i1.ytimg.com/vi/YJeHWZEzLJI/mqdefault.jpg">
                <img class="img-responsive compact-carousel" src="http://i1.ytimg.com/vi/YJeHWZEzLJI/mqdefault.jpg">
                <img class="img-responsive compact-carousel" src="http://i1.ytimg.com/vi/YJeHWZEzLJI/mqdefault.jpg">
                <img class="img-responsive compact-carousel" src="http://i1.ytimg.com/vi/YJeHWZEzLJI/mqdefault.jpg">
              </div>
              <div class="item">
                <img class="img-responsive compact-carousel" src="http://i1.ytimg.com/vi/YJeHWZEzLJI/mqdefault.jpg">
                <img class="img-responsive compact-carousel" src="http://i1.ytimg.com/vi/YJeHWZEzLJI/mqdefault.jpg">
                <img class="img-responsive compact-carousel" src="http://i1.ytimg.com/vi/YJeHWZEzLJI/mqdefault.jpg">
                <img class="img-responsive compact-carousel" src="http://i1.ytimg.com/vi/YJeHWZEzLJI/mqdefault.jpg">
              </div>
        </div>
        <!-- Controls -->
        <a class="left carousel-control compact-slide" href=".carousel" role="button" data-slide="prev">
            <span class="fa fa-2x fa-angle-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control compact-slide" href=".carousel" role="button" data-slide="next">
            <span class="fa fa-2x fa-angle-right"></span>
            <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
{% endblock %}

core/templates/google12b3f70da4511395.html
google-site-verification: google12b3f70da4511395.html

core/templates/store.html
{% extends 'base.html' %}

{% block title %}
    Contato | {{block.super}}
{% endblock %}

{% load static %}

{% block container %}
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 contato">
        <a target="_blank" href="https://api.whatsapp.com/send?phone=5581999407622&text=Ol%C3%A1%21%20Gostaria%20de%20anunciar%20no%20FABR%20Network%21">
            <img class="img-responsive" src="{% static 'img/store/banner-store.jpg' %}">
        </a>
    </div>
</div>
{% endblock %}