fabrnetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core import views

urlpatterns = [
    path(r'manutencao/', views.manutencao, name='manutencao'),
	path(r'', views.index, name='index'),
    path(r'compare/', views.compare, name='compare'),
    path(r'compactos/', views.compacts, name='compacts'),
    path(r'contato/', views.contact, name='contact'),
    path(r'campeonatos/', include('championship.urls', namespace='championship')),
    path(r'estatisticas/', include('statistic.urls', namespace='statistic')),
    path(r'times/', include('team.urls', namespace='team')),
	path(r'noticias/', include('news.urls', namespace='news')),
    path(r'loja/', views.store, name='store'),
    path('admin/', admin.site.urls),
    path(r'summernote/', include('django_summernote.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path, re_path

from . import views

app_name = 'news'

urlpatterns = [
    path('', views.news_list, name='news_list'),
    re_path(r'^(?P<slug>[\w_-]+)/$', views.news, name='news'),
]

team/urls.py
from django.urls import path, re_path

from . import views

app_name = 'team'

urlpatterns = [
    #Outros templates
    re_path(r'^$', views.teams, name='teams'),
    re_path(r'^divisao/(?P<slug>[\w_-]+)/$', views.teams_category, name='teams_category'),
    re_path(r'^compare/$', views.LikenView, name='liken'),
    re_path(r'^(?P<slug>[\w_-]+)/$', views.ScheduleListView, name='team'),
    re_path(r'^(?P<slug>[\w_-]+)/elenco/$', views.RosterView, name='roster'),
    re_path(r'^(?P<slug>[\w_-]+)/agenda/$', views.ScheduleListView, name='schedule'),
    re_path(r'^(?P<slug>[\w_-]+)/agenda/(?P<year>[\w_-]+)$', views.ScheduleByYearView, name='schedule_year'),
    re_path(r'^(?P<slug>[\w_-]+)/compactos/$', views.CompactListView, name='compact'),
    re_path(r'^(?P<slug>[\w_-]+)/campanhas/$', views.CampaignDatailView, name='campaign'),
    re_path(r'^(?P<slug>[\w_-]+)/instagram/$', views.InstagramDetailView, name='instagram'),
    re_path(r'^(?P<slug>[\w_-]+)/facebook/$', views.FacebookDetailView, name='facebook'),
    re_path(r'^(?P<slug>[\w_-]+)/historia/$', views.HistoryDetailView, name='history'),
    re_path(r'^(?P<slug>[\w_-]+)/(?P<playerSlug>[\w_-]+)/$', views.player, name='player'),
]

team/models.py
from django.db import models
from autoslug import AutoSlugField

from core.models import Region, State, City

class TeamCategory (models.Model):
    name = models.CharField('Nome', max_length=255, unique=True)
    
    created = models.DateTimeField('Criado', auto_now_add=True)
    modified = models.DateTimeField('Modificado', auto_now=True)

    class Meta:
        verbose_name = 'Divisão do time'
        verbose_name_plural = '0. Divisões dos times'
        ordering = ['id', 'name']

    def __str__(self):
        return self.name


class SubTeam (models.Model):
    name = models.CharField('Nome', max_length=255, unique=True)
    
    created = models.DateTimeField('Criado', auto_now_add=True)
    modified = models.DateTimeField('Modificado', auto_now=True)

    class Meta:
        verbose_name = 'Especialidade'
        verbose_name_plural = '4. Especialidades'
        ordering = ['id', 'name']

    def __str__(self):
        return self.name

class Team (models.Model):

    name = models.CharField('Nome', max_length=255, unique=True)
    shortName = models.CharField('Nome abreviado', max_length=255)
    initials = models.CharField('Sigla', max_length=3)
    slug = AutoSlugField('Identificador', populate_from='name',
                         max_length=255, unique=True, always_update=True)
    logo = models.ImageField('Logo', upload_to='logos/', null=True, blank=True)
    category = models.ForeignKey(TeamCategory, 
                on_delete=models.CASCADE, null=True, blank=True, 
                verbose_name='Divisão')
    foundation = models.DateField('Data de fundação', null=True, blank=True)

    city = models.ForeignKey(
        City, on_delete=models.CASCADE, verbose_name='Cidade')

    facebook = models.URLField(
        'Facebook', max_length=255, null=True, blank=True)
    instagram = models.URLField(
        'Instagram', max_length=255, null=True, blank=True)

    primaryColor = models.CharField(
        'Cor primária', max_length=20, null=True, blank=True)
    secundaryColor = models.CharField(
        'Cor secundária', max_length=20, null=True, blank=True)
    terciaryColor = models.CharField(
        'Cor terciária', max_length=20, null=True, blank=True)

    created = models.DateTimeField('Criado', auto_now_add=True)
    modified = models.DateTimeField('Modificado', auto_now=True)

    class Meta:
        verbose_name = 'Time'
        verbose_name_plural = '1. Times'
        ordering = ['name']

    def __str__(self):
        return self.name


class Position (models.Model):
    name = models.CharField('Nome', max_length=100)
    initials = models.CharField('Sigla', max_length=10)

    class Meta:
        verbose_name = 'Posição'
        verbose_name_plural = '3. Posições'
        ordering = ['name']

    def __str__(self):
        return self.name


class Player (models.Model):

    name = models.CharField('Nome', max_length=255)
    nickname = models.CharField(
        'Apelido', max_length=255, null=True, blank=True)
    slug = AutoSlugField('Identificador', populate_from='name',
                         max_length=255, unique=True, always_update=True)
    photo = models.ImageField(
        'Foto', upload_to='players/photo/', null=True, blank=True)
    number = models.IntegerField('Número da camisa', null=True, blank=True)
    team = models.ForeignKey(
        Team, on_delete=models.CASCADE, verbose_name='Time', null=True, blank=True)
    position = models.ForeignKey(
        Position, on_delete=models.CASCADE, verbose_name='Posição', null=True, blank=True)
    height = models.DecimalField(
        'Altura', decimal_places=2, max_digits=4, null=True, blank=True)
    weight = models.DecimalField(
        'Peso', decimal_places=2, max_digits=5, null=True, blank=True)
    birthdate = models.DateField('Data de nascimento', null=True, blank=True)

    facebook = models.URLField(
        'Facebook', max_length=255, null=True, blank=True)
    instagram = models.URLField(
        'Instagram', max_length=255, null=True, blank=True)

    experience = models.DateField('Experiência', null=True, blank=True)

    created = models.DateTimeField('Criado', auto_now_add=True)
    modified = models.DateTimeField('Modificado', auto_now=True)

    class Meta:
        verbose_name = 'Jogador'
        verbose_name_plural = '2. Jogadores'
        ordering = ['name']

    def __str__(self):
        return self.name

team/forms.py
from django import forms
from .models import Team, Player

class TeamForm (forms.ModelForm):
	class Meta:
		model = Team
		fields = '__all__'

class PlayerForm (forms.ModelForm):
	class Meta:
		model = Player
		fields = '__all__'

team/views.py
from django.shortcuts import render
from django.views import generic
from .models import Team, Player, TeamCategory
from datetime import datetime
from django.db.models import Q

from championship.models import Season, Round, Game
# Create your views here.

def teams(request):
    return teams_category(request, 'elite')

def teams_category(request, slug):
    category = TeamCategory.objects.get(name=slug.capitalize())

    context = {
        'categories': TeamCategory.objects.all(),
        'category': category,
        'teams':Team.objects.filter(category=category)
    }
    return render(request, 'teams.html', context)

class RosterListView(generic.DetailView):
    model = Team
    template_name = 'roster.html'
    context_object_name = 'team'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['roster'] = Player.objects.filter(team=self.object)
        context['weakName'] = self.object.name.replace(self.object.shortName, '')
        return context

RosterView = RosterListView.as_view()


class ScheduleListView(generic.DetailView):
    model = Team
    template_name = 'schedule.html'
    context_object_name = 'team'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        year = datetime.today().year
        seasons_filter = list(range(year, 2008, -1))
        seasons_filter.remove(2020)

        seasons = Season.objects.filter(year=seasons_filter[0])
        weeks = []
        for season in seasons:
            weeks = weeks + list(Round.objects.filter(season=season))
        
        context['games'] = Game.objects.filter((Q(teamA=self.object) | Q(teamB=self.object)) & Q(week__in=weeks)).order_by('week')
        context['current_season'] = seasons_filter[0]
        seasons_filter.remove(seasons_filter[0])
        context['seasons'] = seasons_filter
        
        return context

ScheduleListView = ScheduleListView.as_view()


class ScheduleByYearListView(generic.DetailView):
    model = Team
    template_name = 'schedule.html'
    context_object_name = 'team'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        year = datetime.today().year
        seasons_filter = list(range(year, 2008, -1))
        seasons_filter.remove(2020)
        seasons_filter.remove(int(self.kwargs.get('year', None)))

        seasons = Season.objects.filter(year=self.kwargs.get('year', None))
        weeks = []
        for season in seasons:
            weeks = weeks + list(Round.objects.filter(season=season))
        
        context['games'] = Game.objects.filter((Q(teamA=self.object) | Q(teamB=self.object)) & Q(week__in=weeks)).order_by('week')
        context['current_season'] = self.kwargs.get('year', None)
        context['seasons'] = seasons_filter
        return context

ScheduleByYearView = ScheduleByYearListView.as_view()

class CompactListView(generic.DetailView):
    model = Team
    template_name = 'compact.html'
    context_object_name = 'team'

CompactListView = CompactListView.as_view()

class InstagramDetailView(generic.DetailView):
    model = Team
    template_name = 'instagram.html'
    context_object_name = 'team'

InstagramDetailView = InstagramDetailView.as_view()

class FacebookDetailView(generic.DetailView):
    model = Team
    template_name = 'facebook.html'
    context_object_name = 'team'

FacebookDetailView = FacebookDetailView.as_view()


class HistoryDetailView(generic.DetailView):
    model = Team
    template_name = 'history.html'
    context_object_name = 'team'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titles'] = Season.objects.filter(
            champion__name=self.object.name)
        return context

HistoryDetailView = HistoryDetailView.as_view()


class CampaignDatailView(generic.DetailView):
    model = Team
    template_name = 'campaign.html'

CampaignDatailView = CampaignDatailView.as_view()


def player(request, slug, playerSlug):
    team = Team.objects.get(slug=slug)
    player = Player.objects.get(slug=playerSlug)

    if player.birthdate:
        idade = datetime.now().year - player.birthdate.year
    else:
        idade = None
    context = {
        'team': team,
        'player': player,
        'idade': idade,
    }

    return render(request, 'player.html', context)


def LikenView(request):
    context = {
        'title': 'Compare',
    }
    return render(request, 'liken.html', context)

team/templates/base_team.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
	{{team.name}} | {{block.super}}
{% endblock %}

{% block container %}
	<style type="text/css">
		:root{
			--primaryColor: {{ team.primaryColor }};
			--secundaryColor: {{ team.secundaryColor }};
			--terciaryColor: {{ team.terciaryColor }};
		}

	</style>

	<div class="page-header" id="banner">
        <div class="row">
        	<div class="col-lg-12 col-md-12 col-sm-12">
	    		<div class="banner-team">
        			<img class="img-responsive banner-team-logo" src="{% if team.logo %} {{team.logo.url}} {% endif %}"/>
        			<div class="molde hidden-sm hidden-xs">
        				<img class="img-responsive banner-team-transparent-logo" src="{% if team.logo %} {{team.logo.url}} {% endif %}"/>
        			</div>
        			<p class="banner-team-city">{{weakName}}</p>
        			<p class="banner-team-name">{{team.shortName}} - {{team.city.uf}}</p>
        			<a href="{{team.facebook}}" target="_blank" class="fa fa-lg fa-facebook-square social-media-banner"></a>
        			<a href="{{team.instagram}}" target="_blank" class="fa fa-lg fa-instagram social-media-banner"></a>
        		</div>
				<div class ="col-lg-3 col-md-3 col-sm-3">
					<ul class="menu-team">
						<a href="{% url 'team:schedule' slug=team.slug %}"><li>Agenda<i class="fa fa-lg fa-angle-right pull-right"></i></li></a>
						<a href="{% url 'team:roster' slug=team.slug %}"><li>Elenco<i class="fa fa-lg fa-angle-right pull-right"></i></li></a>
						<!--<li><a href="">Estatísticas<i class="fa fa-lg fa-angle-right pull-right"></i></a></li>
						<li><a href="{% url 'team:schedule' slug=team.slug %}">Agenda<i class="fa fa-lg fa-angle-right pull-right"></i></a></li>
						<li><a href="{% url 'team:compact' slug=team.slug %}">Compactos<i class="fa fa-lg fa-angle-right pull-right"></i></a></li>
						<li><a href="{% url 'team:campaign' slug=team.slug %}">Campanhas<i class="fa fa-lg fa-angle-right pull-right"></i></a></li>
						-->
						{% if team.facebook %}
						<a href="{% url 'team:facebook' slug=team.slug %}"><li>Facebook<i class="fa fa-lg fa-angle-right pull-right"></i></li></a>
						{% endif %}
						<a href="{% url 'team:history' slug=team.slug %}"><li>História<i class="fa fa-lg fa-angle-right pull-right"></i></li></a>
					</ul>		
				</div>
				<div class="col-lg-9 col-md-9 col-sm-12">
					{% block middle %} {% endblock %}	
				</div>
			</div>
		</div>
	</div>
{% endblock %}

team/templates/campaign.html
{% extends 'base_team.html' %}

{% load static %}

{% block middle %}
	<div class="btn-group" style="margin-bottom:30px;">
		<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"> <span id="selected">Campeonato</span><br/>
		<span class="selected-item">BR</span>
		<i class="fa fa-xs fa-angle-down selected-angle"></i>
		</button>
		<ul class="dropdown-menu dropdown-team">
		    <li><a href="#">BR</a></li>
		    <li><a href="#">Estadual</a></li>
		</ul>
	</div>

	<table class="table table-striped">
		<thead class="table-header">
		    <tr>
		      <th>Temporada</th>
		      <th>Campeonato</th>
		      <th>Posição</th>
		      <th>V</th>
		      <th>D</th>
		      <th>P+</th>
		      <th>P-</th>
		      <th>S</th>
		    </tr>
		 </thead>

		<tbody>
			<tr>
				<td>2018</td>
				<td>BFA</td>
				<td>2º</td>
				<td>7</td>
				<td>2</td>
				<td>114</td>
				<td>100</td>
				<td>14</td>
			</tr>
			<tr>
				<td>2017</td>
				<td>LNFA</td>
				<td>1º</td>
				<td>6</td>
				<td>0</td>
				<td>223</td>
				<td>10</td>
				<td>14</td>
			</tr>
			<tr>
				<td>2016</td>
				<td>LNFA</td>
				<td>6º</td>
				<td>3</td>
				<td>3</td>
				<td>87</td>
				<td>117</td>
				<td>14</td>
			</tr>
			<tr>
				<td>2015</td>
				<td>LFA</td>
				<td>2º</td>
				<td>7</td>
				<td>2</td>
				<td>114</td>
				<td>100</td>
				<td>14</td>
			</tr>
			<tr>
				<td>2014</td>
				<td>LNFA</td>
				<td>1º</td>
				<td>6</td>
				<td>0</td>
				<td>223</td>
				<td>10</td>
				<td>14</td>
			</tr>
			<tr>
				<td>2013</td>
				<td>LNFA</td>
				<td>6º</td>
				<td>3</td>
				<td>3</td>
				<td>87	</td>
				<td>117</td>
				<td>14</td>
			</tr>
			
		</tbody>		
	</table>

{% endblock %}

team/templates/compact.html
{% extends 'base_team.html' %}

{% load static %}

{% block middle %}
<div class="btn-group" style="margin-bottom:30px;">
	<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"> <span id="selected">Temporada</span><br/>
	<span class="selected-item">2018</span>
	<i class="fa fa-xs fa-angle-down selected-angle"></i>
	</button>
	<ul class="dropdown-menu dropdown-team">
	    <li><a href="#">2017</a></li>
	    <li><a href="#">2016</a></li>
	    <li><a href="#">2015</a></li>
	</ul>
</div>

<iframe class="col-lg-12 col-md-12 col-sm-12 col-xs-12 watch" height="315" src="https://www.youtube.com/embed/YJeHWZEzLJI" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

<div class="watch-more">
	<p> ASSISTA TAMBÉM </p>
	<div class="row">
		<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
    	<iframe class="col-lg-8 col-md-8 col-sm-8 col-xs-8 watch" height="315" src="https://www.youtube.com/embed/YJeHWZEzLJI" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    	<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
    </div>

    <div class="row">
    	<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
    	<iframe class="col-lg-8 col-md-8 col-sm-8 col-xs-8 watch" height="315" src="https://www.youtube.com/embed/YJeHWZEzLJI" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
		<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
    </div>

    <div class="row">
		<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
    	<iframe class="col-lg-8 col-md-8 col-sm-8 col-xs-8 watch" height="315" src="https://www.youtube.com/embed/YJeHWZEzLJI" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    	<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
    </div>

    <div class="col-lg-2 col-md-2 col-sm-2"></div>
	<div class="col-lg-8 col-md-8 col-sm-8 read-more-link"><a href="{% url 'team:team' slug=team.slug %}"><i class="fa fa-chevron-down"></i></a></div>
	<div class="col-lg-2 col-md-2 col-sm-2"></div>
</div>

{% endblock %}

team/templates/facebook.html
{% extends 'base_team.html' %}

{% load static %}

{% block middle %}
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v3.2"></script>


<div class="fb-page" data-href="{{team.facebook}}" data-tabs="timeline" data-width="700" data-small-header="true" data-adapt-container-width="true" data-hide-cover="true" data-show-facepile="true">
    <blockquote cite="{{team.facebook}}" class="fb-xfbml-parse-ignore">
        <a href="{{team.facebook}}">{{team.name}}</a>
    </blockquote>
</div>
{% endblock %}

team/templates/history.html
{% extends 'base_team.html' %}

{% load static %}

{% block middle %}
	<table class="table table-history">
		<tbody>
			<tr>
				<td class="col-lg-4 col-md-3 col-sm-3 col-xs-3" id="col">Fundação</td>
				<td class="col-lg-8 col-md-9 col-sm-9 col-xs-9">
					{% if team.foundation %}
						{{ team.foundation }}
					{% endif %}
				</td>
			</tr>
			<tr>
				<td class="col-lg-4 col-md-3 col-sm-3 col-xs-3" id="col">Cidade</td>
				<td class="col-lg-8 col-md-9 col-sm-9 col-xs-9">{{ team.city }}</td>
			</tr>
			<tr>
				<td class="col-lg-4 col-md-3 col-sm-3 col-xs-3" id="col">Títulos</td>
				<td class="col-lg-8 col-md-9 col-sm-9 col-xs-9">
					{% for trophy in titles %}
						{{ trophy }} {% if not forloop.last %},  {% endif %}
					{% endfor %}
				</td>
			</tr>
		</tbody>		
	</table>

{% endblock %}

team/templates/roster.html
{% extends 'base_team.html' %}

{% load static %}

{% block middle %}
	<table class="table table-striped table-hover">
		<thead class="table-header">
		    <tr>
		      <th style="text-align:left">Jogador</th>
		      <th>Número</th>
		      <th>Posição</th>
		    </tr>
		 </thead>
  		<tbody>
	  		{% if roster %}
	  			{% for player in roster %}
				    <tr>
						<td id="playerName" style="text-align:left"><a href="{% url 'team:player' slug=team.slug playerSlug=player.slug %}">{{player.name}}</a></td>
						<td>{{player.number}}</td>
						<td>{{player.position.initials}}</td>
					</tr>
				{% endfor %}
			{% endif %}
		</tbody>		
	</table>

{% endblock %}

team/templates/schedule.html
{% extends 'base_team.html' %}

{% load static %}
{% load dayBefore %}

{% block middle %}
<div class="row">
	<div class="btn-group" style="margin-bottom:30px;">
		<button type="button" 	class="btn btn-default dropdown-toggle" data-toggle="dropdown"> <span id="selected">Temporada</span><br/>
		<span class="selected-item">{{ current_season }}</span>
		<i class="fa fa-xs fa-angle-down selected-angle"></i>
		</button>
		<ul class="dropdown-menu dropdown-team">
            {% for season in seasons %}
                <li><a href="{% url 'team:schedule_year' slug=team.slug year=season %}">{{season}}</a></li>
            {% endfor %}
        </ul>
	</div>
</div>
<div class="row">
	
	{% for game in games %}
		<ul class="list-inline schedule">
			<li class="date-schedule align-middle">
				{% dayBefore game.week.week %}/{{game.week.week|date:'d F'}}
			</li>
			<li class="game-schedule">
				<img class="mini-photo" src="{% if game.teamA.logo %} {{game.teamA.logo.url}} {% endif %}"/> {{game.teamA.shortName}} 
				<div class="score-schedule">{% if game.ended %} {{ game.scoreA }} {% endif %}</div>
				<div style="font-size:12pt; font-family:bebas neue; display:inline-block;vertical-align:middle; padding-top:5px;">x</div>
				<div class="score-schedule">{% if game.ended %} {{ game.scoreB }} {% endif %}</div>
				{{game.teamB.shortName}}<img class="mini-photo" src="{% if game.teamB.logo %} {{game.teamB.logo.url}} {% endif %}"/>
			
			</li>
		</ul>
	{% endfor %}
</div>
{% endblock %}

team/templates/teams.html
{% extends 'base.html' %}

{% block title %}
    Times | {{block.super}}
{% endblock %}

{% load static %}


{% block container %}
    <div class="page-header" id = "banner">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="row" style="margin-bottom: 20px">
                <div class="col-lg-5 col-md-5 col-sm-5 col-xs-3"></div>
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" style="padding-right: 45px"> <span id="selected">Divisão</span><br/>
                            <span class="selected-item">{{ category.name }}</span>
                            <i class="fa fa-xs fa-angle-down selected-angle"></i>
                        </button>
                        <ul class="dropdown-menu dropdown-team">
                            {% for c in categories %}
                                {% if c != category %}
                                    <li><a href="{% url 'team:teams_category' slug=c.name %}">{{ c.name }}</a></li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="col-lg-5 col-md-5 col-sm-5 col-xs-3"></div>
            </div>

            <div class="row">
                <div class="card card-body">
                    <ul class="list-inline">    
                        {% for team in teams %}
                            <li>
                                <a href="{% url 'team:team' slug=team.slug %}" ><img title="{{ team.name }}" src="{% if team.logo %} {{team.logo.url}} {% endif %}" class="list-teams"></a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
  </div>
{% endblock %}